name: Deploy with Pulumi

# trigger on push to main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # if: contains(github.event.comment.body, '/deploy') && github.event.comment.user.login == github.repository_owner
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install Pulumi CLI
      run: |
        curl -fsSL https://get.pulumi.com | sh
        echo "$HOME/.pulumi/bin" >> $GITHUB_PATH

    - name: Debug Event
      run: |
        echo "Event: ${{ toJson(github.event) }}"
        echo "Comment: ${{ github.event.comment.body }}"
        echo "User: ${{ github.event.comment.user.login }}"
        echo "Owner: ${{ github.repository_owner }}"
